### ISSUE TITLE
`log.Print` fails

### ISSUE THREAD

**Issue by hajimehoshi** [neelance/go#26] opened 2018-06-08 16:38 UTC
```go
package main

import (
        "log"
)

func main() {
        log.Print("foo")
}
```

```
panic: JavaScript error: Function.prototype.apply was called on undefined, which is a undefined and not a function [recovered]
wasm_exec.js:41 	panic: JavaScript error: Function.prototype.apply was called on undefined, which is a undefined and not a function
wasm_exec.js:41 
wasm_exec.js:41 goroutine 1 [running]:
wasm_exec.js:41 syscall.recoverErr(0xc04a9c8)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/syscall/fs_js.go:493 +0x29
wasm_exec.js:41 panic(0x24720, 0xc01c01c)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/runtime/panic.go:494 +0x1d
wasm_exec.js:41 syscall/js.Value.Call(0xc, 0x2b07b, 0x8, 0xc04aa60, 0x3, 0x3, 0xc0281f0)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/syscall/js/js.go:144 +0x7
wasm_exec.js:41 syscall.fsCall(0x2b07b, 0x8, 0xc04aa60, 0x3, 0x3, 0x0, 0x0, 0x0)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/syscall/fs_js.go:468 +0x4
wasm_exec.js:41 syscall.Open(0xc01c020, 0xf, 0x0, 0x0, 0x9, 0xf, 0xc01c020)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/syscall/fs_js.go:88 +0x17
wasm_exec.js:41 time.open(0xc01c020, 0xf, 0xf, 0x9, 0x9)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/time/sys_unix.go:20 +0x2
wasm_exec.js:41 time.readFile(0xc01c020, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/time/zoneinfo_read.go:413 +0x2
wasm_exec.js:41 time.loadTzinfoFromDirOrZip(0x2a905, 0x5, 0x2b2ac, 0x9, 0xc000180, 0xc02a200, 0xc00e070, 0x140c0003, 0x1472c8)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/time/zoneinfo_read.go:233 +0xa
wasm_exec.js:41 time.loadTzinfo(0x2b2ac, 0x9, 0x2a905, 0x5, 0x14170003, 0x147310, 0xffffffff, 0x0, 0x14350015)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/time/zoneinfo_read.go:383 +0xa
wasm_exec.js:41 time.loadLocation(0x2b2ac, 0x9, 0xc04acd8, 0x1, 0x1, 0x1195000a, 0xc02a1f0, 0xc022500)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/time/zoneinfo_read.go:392 +0x6
wasm_exec.js:41 time.initLocal()
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/time/zoneinfo_unix.go:37 +0x16
wasm_exec.js:41 sync.(*Once).Do(0x1472d8, 0x31430)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/sync/once.go:44 +0xe
wasm_exec.js:41 time.(*Location).get(0x12d100, 0x8)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/time/zoneinfo.go:79 +0x5
wasm_exec.js:41 time.Time.abs(0xbebeca1b46dac2c0, 0x3cf0901, 0x12d100, 0x3)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/time/time.go:452 +0x4
wasm_exec.js:41 time.Time.date(0xbebeca1b46dac2c0, 0x3cf0901, 0x12d100, 0x16610001, 0xc044000, 0x2a78a, 0x3, 0x76)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/time/time.go:947 +0x2
wasm_exec.js:41 time.Time.Date(0xbebeca1b46dac2c0, 0x3cf0901, 0x12d100, 0x0, 0x1, 0xc000180)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/time/time.go:492 +0x2
wasm_exec.js:41 log.(*Logger).formatHeader(0xc040000, 0xc040030, 0xbebeca1b46dac2c0, 0x3cf0901, 0x12d100, 0x0, 0x0, 0x0)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/log/log.go:103 +0x5e
wasm_exec.js:41 log.(*Logger).Output(0xc040000, 0x2, 0xc01c018, 0x3, 0x0, 0x0)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/log/log.go:167 +0x9
wasm_exec.js:41 log.Print(0xc022788, 0x1, 0x1)
wasm_exec.js:41 	/Users/hajimehoshi/go-code/src/log/log.go:289 +0x3
wasm_exec.js:41 main.main()
wasm_exec.js:41 	/Users/hajimehoshi/test/wasm/test.go:8 +0x2
```

**Comment by neelance** [comment] 2018-06-14 22:01
Works for me with Node.js on latest `wasm-wip`. Could you please check again?

**Comment by neelance** [comment] 2018-06-14 22:02
Able to reproduce with Chrome. Looking into it...

**Comment by neelance** [comment] 2018-06-14 22:13
Fixed on `wasm-wip`.

**Closed by neelance** 2018-06-14 22:13 UTC
